# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.10-stretch-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Generate credentials.js
      - run: .circleci/generate-credentials.sh

      # Make a production build
      - run: yarn build

      # Store the artifacts to workspace
      - persist_to_workspace:
          root: dist
          paths:
            - client
            - lambda.zip

  deploy:
    docker:
      - image: circleci/node:9.10-stretch-browsers

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: dist

      - run: sudo apt -yqq update
      - run: sudo apt -yqq install awscli
      - run: aws s3 sync --delete dist/client s3://kunvet-prod-client/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
