const categoryPositionMap = [
  { 'category': 'No preference',
    'positions': ['no preference'] },
  { 'category': 'Business, Finance, Management, HR',
    'positions': ['business planner', 'co-founder', 'entrepreneur', 'event coordinator', 'financial services provider', 'general manager', 'human resources manager', 'human resources specialists', 'investment banker', 'leadership', 'manager', 'mortgage banker', 'project manager', 'real estate agent', 'recruiter', 'shift leader', 'supervisor', 'quality controller'] },
  { 'category': 'Marketing, Sales',
    'positions': ['bookseller', 'brand ambassador', 'call representative', 'customer service person', 'event coordinator', 'insurance agent', 'marketer', 'online marketer', 'outreach specialist', 'outreach worker', 'retailer', 'sales', 'social media marketer', 'telemarketer', 'nutrition specialist'] },
  { 'category': 'Services, Food, Hospitality, Lifeguard',
    'positions': ['babysitter', 'barista', 'bartender', 'caregiver', 'cashier', 'chef', 'cook', 'dishwasher', 'event coordinator', 'food server', 'front desk', 'host', 'hostess', 'housekeeper', 'inventory associate', 'janitor', 'kitchen staff', 'lab assistant', 'library monitor', 'notetakers', 'personal care attendant', 'pizzaiolo', 'receptionist', 'sandwich maker', 'waiter', 'waitress', 'call representative', 'lifeguard', 'operations associate', 'parking attendant'] },
  { 'category': 'Medical, Pharmacy, Dental',
    'positions': ['dental assistant', 'medical assistant', 'personal care attendant'] },
  { 'category': 'Programming, Development',
    'positions': ['backend developer', 'computer engineer', 'frontend developer', 'iOS developer', 'IT assistant', 'lead developer', 'programmer', 'software developer', 'software engineer', 'technical artist', 'technical services specialist', 'web designer', 'web developer'] },
  { 'category': 'Constructions, Labor, Housekeeping',
    'positions': ['exterior painter', 'inventory associate', 'janitor', 'housekeeper', 'operations associate'] },
  { 'category': 'Writing, Copy, Literature',
    'positions': ['content writer', 'copy editor', 'editorial assistant', 'notetakers', 'technical writer', 'underwriter'] },
  { 'category': 'Accounting, Bookkeeping',
    'positions': ['accountant', 'bookkeeper'] },
  { 'category': 'Assistant',
    'positions': ['administrative assistant', 'appointment setter', 'assistant manager', 'business planner', 'customer service person', 'editorial assistant', 'event coordinator', 'front desk', 'general assistant', 'inventory associate', 'lab assistant', 'library monitor', 'notetakers', 'office assistant', 'planner', 'receptionist', 'quality controller'] },
  { 'category': 'Data Analyst, Data Management',
    'positions': ['analyst', 'business analyst', 'data analyst', 'financial analyst'] },
  { 'category': 'Driving, Delivery',
    'positions': ['bus driver', 'consignor', 'delivery man', 'driver', 'shipper', 'shuttle operator', 'truck driver'] },
  { 'category': 'Design, Graphics, Arts',
    'positions': ['designer', 'graphic designer', 'web designer'] },
  { 'category': 'Engineering, IT',
    'positions': ['computer engineer', 'electrical engineer', 'IT assistant', 'material science engineer', 'mechanical designer', 'mechanical engineer', 'technical artist', 'technical services specialist', 'technician'] },
  { 'category': 'Tutor, Teacher, Education',
    'positions': ['counselor', 'education', 'mentor', 'preschool teacher', 'SAT/ACT teacher', 'teacher', 'tutor'] },
  { 'category': 'Photography, Film, Video Editing',
    'positions': ['film editor', 'video editing', 'photographer'] },
  { 'category': 'Volunteer',
    'positions': ['volunteer'] },
];

export default categoryPositionMap;
