const positions = [
  'accountant',
  'administrative assistant',
  'analyst',
  'appointment setter',
  'assistant manager',
  'babysitter',
  'backend developer',
  'barista',
  'bartender',
  'bookkeeper',
  'bookseller',
  'brand ambassador',
  'bus driver',
  'business analyst',
  'business planner',
  'call representative',
  'caregiver',
  'cashier',
  'chef',
  'computer engineer',
  'content writer',
  'consignor',
  'cook',
  'copy editor',
  'counselor',
  'customer service person',
  'data analyst',
  'delivery man',
  'dental assistant',
  'designer',
  'dishwasher',
  'driver',
  'editorial assistant',
  'education',
  'electrical engineer',
  'event coordinator',
  'exterior painter',
  'film editor',
  'financial analyst',
  'financial services provider',
  'food server',
  'front desk',
  'frontend developer',
  'general assistant',
  'general manager',
  'graphic designer',
  'host',
  'hostess',
  'housekeeper',
  'human resources manager',
  'human resources specialists',
  'insurance agent',
  'inventory associate',
  'investment banker',
  'IT assistant',
  'janitor',
  'kitchen staff',
  'lab assistant',
  'lead developer',
  'leadership',
  'library monitor',
  'manager',
  'marketer',
  'material science engineer',
  'mechanical designer',
  'mechanical engineer',
  'medical assistant',
  'mentor',
  'mortgage banker',
  'musician',
  'notetakers',
  'nutrition specialist',
  'office assistant',
  'online marketer',
  'operations associate',
  'outreach specialist',
  'outreach worker',
  'parking attendant',
  'personal care attendant',
  'photographer',
  'pizzaiolo',
  'planner',
  'preschool teacher',
  'programmer',
  'project manager',
  'quality controller',
  'real estate agent',
  'receptionist',
  'recruiter',
  'researcher',
  'retailer',
  'sales',
  'sandwich maker',
  'SAT/ACT teacher',
  'shift leader',
  'shipper',
  'shuttle operator',
  'social media marketer',
  'software developer',
  'software engineer',
  'supervisor',
  'teacher',
  'technical artist',
  'technical services specialist',
  'technical writer',
  'technician',
  'telemarketer',
  'truck driver',
  'tutor',
  'underwriter',
  'video editing',
  'volunteer',
  'waiter',
  'waitress',
  'web designer',
  'web developer',
];

export default positions;
