const users = [
  { 'email': 'leovinogradov@gmail.com', 'firstname': 'Leo', 'tags': ['customer service person', 'front desk', 'web developer', 'programmer', 'backend developer', 'frontend developer'] },
  { 'email': 'najeeh.allah@gmail.com', 'firstname': 'Na’Jee', 'tags': ['receptionist', 'general assistant', 'driver', 'retailer', 'sales'] },
  { 'email': 'ryanho0906@live.com', 'firstname': 'Thinh', 'tags': ['accountant', 'administrative assistant'] },
  { 'email': 'thelaststerling@gmail.com', 'firstname': 'Ryan', 'tags': ['customer service person'] },
  { 'email': 'jasminessom@yahoo.com', 'firstname': 'Jasmine', 'tags': ['cook'] },
  { 'email': 'jorgebr@uci.edu', 'firstname': 'Jorge', 'tags': ['barista', 'cashier', 'customer service person', 'food server', 'cashier', 'customer service person', 'food server', 'hostess', 'waitress', 'waiter', 'tutor', 'teacher', 'SAT/ACT teacher', 'receptionist', 'caregiver', 'customer service person', 'education', 'babysitter', 'preschool teacher', 'education', 'office assistant', 'general assistant', 'front desk'] },
  { 'email': 'zhaominl@uci.edu', 'firstname': 'Zhaomin', 'tags': ['web designer', 'web developer', 'software developer', 'graphic designer', 'designer'] },
  { 'email': 'atolegen@uci.edu', 'firstname': 'Aigerim', 'tags': ['education', 'counselor', 'caregiver', 'inventory associate', 'operations associate', 'shipper', 'education', 'mentor', 'SAT/ACT teacher', 'teacher', 'tutor'] },
  { 'email': 'vanessachow36@gmail.com', 'firstname': 'Vanessa', 'tags': ['social media marketer', 'online marketer', 'content writer', 'outreach worker', 'administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist', 'administrative assistant', 'business analyst', 'business planner', 'call representative', 'customer service person', 'graphic designer', 'event coordinator', 'project manager', 'receptionist', 'social media marketer'] },
  { 'email': 'xinyiw19@uci.edu', 'firstname': 'Xinyi', 'tags': ['teacher'] },
  { 'email': 'albertz3@uci.edu', 'firstname': 'Albert', 'tags': ['electrical engineer', 'programmer', 'social media marketer', 'software engineer', 'software developer', 'electrical engineer', 'IT assistant', 'web developer', 'programmer', 'backend developer'] },
  { 'email': 'tylera1999@hotmail.com', 'firstname': 'Tyler', 'tags': ['education', 'mentor', 'SAT/ACT teacher', 'teacher', 'tutor', 'babysitter', 'caregiver', 'dishwasher', 'education', 'janitor', 'housekeeper', 'general assistant', 'food server', 'kitchen staff'] },
  { 'email': 'zamash11@gmail.com', 'firstname': 'Sara', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant'] },
  { 'email': 'maryneachieng@gmail.com', 'firstname': 'Marine', 'tags': ['administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist'] },
  { 'email': 'amsahagi@uci.edu', 'firstname': 'Astghik', 'tags': ['assistant manager', 'general manager', 'project manager', 'social media marketer', 'event coordinator', 'brand ambassador', 'general manager', 'leadership', 'marketer', 'online marketer', 'assistant manager', 'content writer', 'video editing', 'marketer', 'general assistant', 'administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist', 'researcher'] },
  { 'email': 'mpande@uci.edu', 'firstname': 'Maithily', 'tags': ['iOS developer', 'software developer', 'software engineer', 'web developer', 'computer engineer', 'cashier', 'customer service person', 'food server', 'hostess', 'waitress', 'waiter', 'tutor', 'teacher', 'SAT/ACT teacher', 'receptionist', 'caregiver', 'customer service person', 'education', 'babysitter', 'preschool teacher', 'education', 'office assistant', 'general assistant', 'front desk'] },
  { 'email': 'agarciar@uci.edu', 'firstname': 'Andres', 'tags': ['iOS developer', 'software developer', 'software engineer', 'web developer', 'computer engineer', 'education', 'mentor', 'SAT/ACT teacher', 'teacher', 'tutor', 'education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant'] },
  { 'email': 'eskandan@uci.edu', 'firstname': 'Naseem', 'tags': ['customer service person', 'administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist', 'assistant manager', 'general manager', 'project manager'] },
  { 'email': 'jcalvin@uci.edu', 'firstname': 'Jordan', 'tags': ['administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist', 'customer service person'] },
  { 'email': 'biensalvania98@gmail.com', 'firstname': 'Bien', 'tags': ['assistant manager', 'general manager', 'project manager'] },
  { 'email': 'edwardlee0117@yahoo.com', 'firstname': 'Seungmin', 'tags': ['education', 'mentor', 'SAT/ACT teacher', 'teacher', 'tutor'] },
  { 'email': 'a777juarez@gmail.com', 'firstname': 'Andrew', 'tags': ['iOS developer', 'software developer', 'software engineer', 'web developer', 'computer engineer'] },
  { 'email': 'nsquach@uci.edu', 'firstname': 'Nghi', 'tags': ['social media marketer', 'online marketer', 'content writer', 'outreach worker', 'administrative assistant', 'business analyst', 'business planner', 'call representative', 'customer service person', 'graphic designer', 'event coordinator', 'project manager', 'receptionist', 'social media marketer'] },
  { 'email': 'liarivera16@gmail.com', 'firstname': 'Lia', 'tags': ['customer service person', 'caregiver', 'social media marketer', 'event coordinator', 'brand ambassador', 'general manager', 'leadership', 'marketer', 'online marketer', 'assistant manager', 'content writer', 'video editing', 'lifeguard', 'education', 'leadership', 'babysitter', 'caregiver', 'dishwasher', 'education', 'janitor', 'housekeeper', 'general assistant', 'food server', 'kitchen staff', 'analyst', 'business analyst', 'data analyst', 'leadership'] },
  { 'email': 'nathanielkarter@gmail.com', 'firstname': 'Nathaniel', 'tags': [] },
  { 'email': 'janellearino@hotmail.com', 'firstname': 'Janelle', 'tags': ['customer service person'] },
  { 'email': 'llvillas@uci.edu', 'firstname': 'Lidia', 'tags': ['social media marketer', 'online marketer', 'content writer', 'outreach worker'] },
  { 'email': 'melhshin91@gmail.com', 'firstname': 'Melvin', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant', 'assistant manager', 'general manager', 'project manager', 'appointment setter', 'social media marketer', 'administrative assistant'] },
  { 'email': 'molinake@uci.edu', 'firstname': 'Karina', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant', 'receptionist', 'administrative assistant', 'front desk', 'accountant', 'administrative assistant'] },
  { 'email': 'laurenthibaut@gmail.com', 'firstname': 'Lauren', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant'] },
  { 'email': 'alvizoj@uci.edu', 'firstname': 'Joseph', 'tags': ['web designer', 'web developer', 'software developer', 'graphic designer', 'designer', 'accountant', 'administrative assistant', 'accountant', 'administrative assistant', 'computer engineer', 'general assistant', 'web developer', 'software engineer', 'operations associate', 'office assistant', 'education', 'counselor', 'caregiver', 'web developer', 'programmer', 'backend developer', 'frontend developer', 'analyst', 'business analyst', 'data analyst', 'leadership', 'inventory associate', 'operations associate', 'shipper'] },
  { 'email': 'justinwn@uci.edu', 'firstname': 'Justin', 'tags': ['administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist'] },
  { 'email': 'bljo.4ever@gmail.com', 'firstname': 'Bill', 'tags': ['outreach worker', 'marketer'] },
  { 'email': 'gabriel.e.villena@gmail.com', 'firstname': 'Gabriel', 'tags': ['inventory associate', 'operations associate', 'shipper'] },
  { 'email': 'jenhajcak@gmail.com', 'firstname': 'Jennifer', 'tags': ['receptionist', 'administrative assistant', 'front desk'] },
  { 'email': 'lpoore@uci.edu', 'firstname': 'Liam', 'tags': ['receptionist', 'administrative assistant', 'front desk', 'administrative assistant', 'customer service person', 'front desk', 'office assistant', 'receptionist', 'education', 'mentor', 'SAT/ACT teacher', 'teacher', 'tutor', 'researcher', 'customer service person', 'education', 'counselor', 'caregiver', 'education', 'counselor', 'caregiver', 'inventory associate', 'operations associate', 'shipper', 'analyst', 'business analyst', 'data analyst', 'leadership'] },
  { 'email': 'thakobia@uci.edu', 'firstname': 'Timothy', 'tags': ['web developer', 'programmer', 'backend developer', 'frontend developer'] },
  { 'email': 'hkoury@uci.edu', 'firstname': 'Hannah', 'tags': ['teacher', 'caregiver'] },
  { 'email': 'mmohame2@uci.edu', 'firstname': 'Mohamed', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant'] },
  { 'email': 'maylinh2k@gmail.com', 'firstname': 'Maylinh', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant'] },
  { 'email': 'yoonsec3@uci.edu', 'firstname': 'Yoonseong', 'tags': ['education', 'front desk', 'general assistant', 'lab assistant', 'tutor', 'teacher', 'preschool teacher', 'office assistant', 'volunteer', 'researcher'] },
  { 'email': 'andyvugovernmentclass@yahoo.com', 'firstname': 'Andy ', 'tags': ['babysitter', 'caregiver', 'dishwasher', 'education', 'janitor', 'housekeeper', 'general assistant', 'food server', 'kitchen staff'] },
  { 'email': 'stevesarabia23@yahoo.com', 'firstname': 'Steve', 'tags': ['driver'] },
  { 'email': 'dizonseana@gmail.com', 'firstname': 'Sean', 'tags': ['teacher'] },
  { 'email': 'caveneg1@uci.edu', 'firstname': 'Cesar', 'tags': ['web developer', 'programmer', 'backend developer'] },
  { 'email': 'berrylantis@gmail.com', 'firstname': 'Haley', 'tags': ['office assistant', 'sales', 'customer service person', 'web developer', 'programmer', 'backend developer'] },
  { 'email': 'asuateng@uci.edu', 'firstname': 'Ana Daniela', 'tags': ['office assistant', 'sales', 'customer service person', 'outreach worker', 'marketer', 'receptionist', 'administrative assistant', 'front desk'] },
  { 'email': 'cleiderg@uci.edu', 'firstname': 'Cleider', 'tags': ['web developer', 'programmer', 'backend developer'] },
  { 'email': 'niva.ranavat@gmail.com', 'firstname': 'Niva', 'tags': ['web developer', 'programmer', 'backend developer'] },
  { 'email': 'ckatapski@gmail.com', 'firstname': 'Connor', 'tags': ['web designer', 'office assistant', 'sales', 'customer service person'] },
  { 'email': 'jhp.hnphan@gmail.com', 'firstname': 'H', 'tags': ['web developer', 'programmer', 'backend developer', 'web designer'] },
  { 'email': 'y.torres8@yahoo.com', 'firstname': 'Yadira', 'tags': ['office assistant', 'sales', 'customer service person'] },
  { 'email': 'yingyuy@uci.edu', 'firstname': 'Yingyu', 'tags': ['web developer', 'programmer', 'backend developer', 'web designer', 'outreach worker', 'marketer'] },
  { 'email': 'guilleeh@uci.edu', 'firstname': 'Guillermo', 'tags': ['web designer'] },
  { 'email': 'skysongkaiyuan@gmail.com', 'firstname': 'Kaiyuan', 'tags': ['social media marketer', 'online marketer', 'content writer', 'outreach worker'] },
  { 'email': 'ctian.2001@gmail.com', 'firstname': 'Chris', 'tags': ['web developer', 'programmer', 'backend developer'] },
  { 'email': 'yxia11@uci.edu', 'firstname': 'Yuan', 'tags': ['web developer', 'programmer', 'backend developer', 'web developer', 'programmer', 'backend developer', 'frontend developer', 'web designer'] },
  { 'email': 'edwardsi@uci.edu', 'firstname': 'Ian Jackson', 'tags': ['lab assistant'] },
  { 'email': 'ikemotom@uci.edu', 'firstname': 'Megan', 'tags': ['lab assistant'] },
  { 'email': 'khanhth@uci.edu', 'firstname': 'Khanh', 'tags': ['lab assistant'] },
  { 'email': 'jbarbere@uci.edu', 'firstname': 'Jessenia', 'tags': ['lab assistant'] },
  { 'email': 'bmminer@uci.edu', 'firstname': 'Brienna', 'tags': ['lab assistant'] },
  { 'email': 'egsosa@uci.edu', 'firstname': 'Edison', 'tags': ['lab assistant'] },
  { 'email': 'melomina@uci.edu', 'firstname': 'Michael Steven', 'tags': ['lab assistant'] },
  { 'email': 'cacarbon@uci.edu', 'firstname': 'Christopher', 'tags': ['lab assistant'] },
  { 'email': 'medinagl@uci.edu', 'firstname': 'Leslie', 'tags': ['lab assistant', 'office assistant', 'sales', 'customer service person'] },
  { 'email': 'leew13@uci.edu', 'firstname': 'William', 'tags': ['lab assistant'] },
  { 'email': 'dojt2@uci.edu', 'firstname': 'Jennifer ', 'tags': ['lab assistant'] },
  { 'email': 'dhassan@uci.edu', 'firstname': 'Dania', 'tags': ['lab assistant'] },
  { 'email': 'merafa@uci.edu', 'firstname': 'Meraf', 'tags': ['lab assistant'] },
  { 'email': 'tamezmorgan@gmail.com', 'firstname': 'Morgan', 'tags': ['lab assistant'] },
  { 'email': 'jrpaine@uci.edu', 'firstname': 'Justyne', 'tags': ['lab assistant'] },
  { 'email': 'anhl8@uci.edu', 'firstname': 'Anh', 'tags': ['lab assistant'] },
  { 'email': 'ashlean2@uci.edu', 'firstname': 'Ashley ', 'tags': ['lab assistant'] },
  { 'email': 'linhkn1@uci.edu', 'firstname': 'Linh', 'tags': ['lab assistant'] },
  { 'email': 'minelas@uci.edu', 'firstname': 'Minela', 'tags': ['lab assistant'] },
  { 'email': 'zixuh@uci.edu', 'firstname': 'ZIXU', 'tags': ['lab assistant'] },
  { 'email': 'jpthai@uci.edu', 'firstname': 'Jacqueline', 'tags': ['lab assistant'] },
  { 'email': 'jkbanh@uci.edu', 'firstname': 'Jessica', 'tags': ['lab assistant'] },
  { 'email': 'kriti.garg510@gmail.com', 'firstname': 'Kriti', 'tags': ['lab assistant'] },
  { 'email': 'atumu@uci.edu', 'firstname': 'Abhinav', 'tags': ['web developer', 'programmer', 'backend developer', 'web developer', 'frontend developer', 'programmer'] },
  { 'email': 'lizandrr@uci.edu', 'firstname': 'Lizandro', 'tags': ['lab assistant'] },
  { 'email': 'mdemehri@uci.edu', 'firstname': 'Mehrnaz', 'tags': ['web developer', 'programmer', 'backend developer'] },
  { 'email': 'priscimn@uci.edu', 'firstname': 'Priscilla', 'tags': ['lab assistant'] },
  { 'email': 'peiyw@uci.edu', 'firstname': 'Natasha', 'tags': ['lab assistant'] },
  { 'email': 'vomm@uci.edu', 'firstname': 'Michael', 'tags': ['web developer', 'frontend developer', 'programmer'] },
  { 'email': 'chenaaron3@gmail.com', 'firstname': 'Aaron', 'tags': ['web developer', 'programmer', 'backend developer', 'web developer', 'frontend developer', 'programmer'] },
  { 'email': 'rxgupta@uci.edu', 'firstname': 'Raman', 'tags': ['web developer', 'frontend developer', 'programmer', 'web developer', 'programmer', 'backend developer'] },
];

export default users;
